### ISSUE TITLE
F-21 Tras actualizar a rails7 bin/rails test produce  stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/sal7711_gen#21]

**Comment by vtamara** [comment]
Tras desactivar simplecov:

bin/rails test                                                                                                   
/var/www/bundler/ruby/3.0/gems/activesupport-7.0.0/lib/active_support/core_ext/object/instance_variables.rb:15:in `map': stack level too deep (SystemStackError)
        from /var/www/bundler/ruby/3.0/gems/activesupport-7.0.0/lib/active_support/core_ext/object/instance_variables.rb:15:in `instance_values'
        from /var/www/bundler/ruby/3.0/gems/activesupport-7.0.0/lib/active_support/core_ext/object/json.rb:63:in `as_json'
        from /var/www/bundler/ruby/3.0/gems/activesupport-7.0.0/lib/active_support/core_ext/object/json.rb:180:in `block in as_json'
        from /var/www/bundler/ruby/3.0/gems/activesupport-7.0.0/lib/active_support/core_ext/object/json.rb:179:in `each'
        from /var/www/bundler/ruby/3.0/gems/activesupport-7.0.0/lib/active_support/core_ext/object/json.rb:179:in `as_json'
        from /var/www/bundler/ruby/3.0/gems/activesupport-7.0.0/lib/active_support/core_ext/object/json.rb:63:in `as_json'
        from /var/www/bundler/ruby/3.0/gems/activesupport-7.0.0/lib/active_support/core_ext/object/json.rb:180:in `block in as_json'
        from /var/www/bundler/ruby/3.0/gems/activesupport-7.0.0/lib/active_support/core_ext/object/json.rb:179:in `each'
         ... 9305 levels...             
        from /var/www/bundler/ruby/3.0/gems/railties-7.0.0/lib/rails/engine/commands.rb:9:in `<top (required)>'
        from /var/www/bundler/ruby/3.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
        from /var/www/bundler/ruby/3.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
        from bin/rails:14:in `<main>'
